
package Pokemones;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class ListaPokemones {
    private final Pokemones [] listaPokemones = new Pokemones[151];
    private final JLabel [] imagenesPokemones = new JLabel[151];
    
    public ListaPokemones() {
    }
    //crear los pokemones y recibir un arreglo de JLabels con las imagenes de c/u
    public Pokemones [] crearPokemones(){
        //primeros 10 pokemones 
        Pokemones p1 = new Pokemones("Bulbasaur", 100, 1);
        Pokemones p2 = new Pokemones("Ivysaur", 100, 1);
        Pokemones p3 = new Pokemones("Venusaur", 100, 1);
        Pokemones p4 = new Pokemones("Charmander", 100, 1);
        Pokemones p5 = new Pokemones("Charmeleon", 100, 1);
        Pokemones p6 = new Pokemones("Charizard", 100, 1);
        Pokemones p7 = new Pokemones("Squirtle", 100, 1);
        Pokemones p8 = new Pokemones("Wartotle", 100, 1);
        Pokemones p9 = new Pokemones("Blastoise", 100, 1);
        Pokemones p10 = new Pokemones("Caterpie", 100, 1);
        listaPokemones[0] = p1;
        listaPokemones[1] = p2;
        listaPokemones[2] = p3;
        listaPokemones[3] = p4;
        listaPokemones[4] = p5;
        listaPokemones[5] = p6;
        listaPokemones[6] = p7;
        listaPokemones[7] = p8;
        listaPokemones[8] = p9;
        listaPokemones[9] = p10;
        //otros 10 pokemones
        Pokemones p11 = new Pokemones("Metapod", 100, 1);
        Pokemones p12 = new Pokemones("Butterfree", 100, 1);
        Pokemones p13 = new Pokemones("Weedle", 100, 1);
        Pokemones p14 = new Pokemones("kakuna", 100, 1);
        Pokemones p15 = new Pokemones("Beedrill", 100, 1);
        Pokemones p16 = new Pokemones("Pidgey", 100, 1);
        Pokemones p17 = new Pokemones("Pidgeotto", 100, 1);
        Pokemones p18 = new Pokemones("pidgeot", 100, 1);
        Pokemones p19 = new Pokemones("Rattata", 100, 1);
        Pokemones p20 = new Pokemones("Raticate", 100, 1);
        listaPokemones[10] = p11;
        listaPokemones[11] = p12;
        listaPokemones[12] = p13;
        listaPokemones[13] = p14;
        listaPokemones[14] = p15;
        listaPokemones[15] = p16;
        listaPokemones[16] = p17;
        listaPokemones[17] = p18;
        listaPokemones[18] = p19;
        listaPokemones[19] = p20;
        Pokemones p21 = new Pokemones("Spearow", 100, 1);
        Pokemones p22 = new Pokemones("Fearow", 100, 1);
        Pokemones p23 = new Pokemones("Ekans", 100, 1);
        Pokemones p24 = new Pokemones("Arbok", 100, 1);
        Pokemones p25 = new Pokemones("Pikachu", 100, 1);
        Pokemones p26 = new Pokemones("Raichu", 100, 1);
        Pokemones p27 = new Pokemones("Sandshrew", 100, 1);
        Pokemones p28 = new Pokemones("Sandslash", 100, 1);
        Pokemones p29 = new Pokemones("Nidoran", 100, 1);
        Pokemones p30 = new Pokemones("Nidorina", 100, 1);
        listaPokemones[20] = p21;
        listaPokemones[21] = p22;
        listaPokemones[22] = p23;
        listaPokemones[23] = p24;
        listaPokemones[24] = p25;
        listaPokemones[25] = p26;
        listaPokemones[26] = p27;
        listaPokemones[27] = p28;
        listaPokemones[28] = p29;
        listaPokemones[29] = p30;
        Pokemones p31 = new Pokemones("Nidoqueen", 100, 1);
        Pokemones p32 = new Pokemones("Nidoran", 100, 1);
        Pokemones p33 = new Pokemones("Nidorino", 100, 1);
        Pokemones p34 = new Pokemones("Nidoking", 100, 1);
        Pokemones p35 = new Pokemones("Clefairy", 100, 1);
        Pokemones p36 = new Pokemones("Clefable", 100, 1);
        Pokemones p37 = new Pokemones("Vulpix", 100, 1);
        Pokemones p38 = new Pokemones("Ninetales", 100, 1);
        Pokemones p39 = new Pokemones("Jigglupuff", 100, 1);
        Pokemones p40 = new Pokemones("Wigglypuff", 100, 1);
        listaPokemones[30] = p31;
        listaPokemones[31] = p32;
        listaPokemones[32] = p33;
        listaPokemones[33] = p34;
        listaPokemones[34] = p35;
        listaPokemones[35] = p36;
        listaPokemones[36] = p37;
        listaPokemones[37] = p38;
        listaPokemones[38] = p39;
        listaPokemones[39] = p40;
        Pokemones p41 = new Pokemones("Zubat", 100, 1);
        Pokemones p42 = new Pokemones("Golbat", 100, 1);
        Pokemones p43 = new Pokemones("Oddish", 100, 1);
        Pokemones p44 = new Pokemones("Gloom", 100, 1);
        Pokemones p45 = new Pokemones("Vileplume", 100, 1);
        Pokemones p46 = new Pokemones("Paras", 100, 1);
        Pokemones p47 = new Pokemones("Parasect", 100, 1);
        Pokemones p48 = new Pokemones("Venonat", 100, 1);
        Pokemones p49 = new Pokemones("Venomoth", 100, 1);
        Pokemones p50 = new Pokemones("Diglett", 100, 1);
        listaPokemones[40] = p41;
        listaPokemones[41] = p42;
        listaPokemones[42] = p43;
        listaPokemones[43] = p44;
        listaPokemones[44] = p45;
        listaPokemones[45] = p46;
        listaPokemones[46] = p47;
        listaPokemones[47] = p48;
        listaPokemones[48] = p49;
        listaPokemones[49] = p50;
        Pokemones p51 = new Pokemones("Dugtrio", 100, 1);
        Pokemones p52 = new Pokemones("Meowth", 100, 1);
        Pokemones p53 = new Pokemones("Persian", 100, 1);
        Pokemones p54 = new Pokemones("Psyduck", 100, 1);
        Pokemones p55 = new Pokemones("Golduck", 100, 1);
        Pokemones p56 = new Pokemones("Mankey", 100, 1);
        Pokemones p57 = new Pokemones("Primeape", 100, 1);
        Pokemones p58 = new Pokemones("Growlithe", 100, 1);
        Pokemones p59 = new Pokemones("Arcaine", 100, 1);
        Pokemones p60 = new Pokemones("Poliwag", 100, 1);
        listaPokemones[50] = p51;
        listaPokemones[51] = p52;
        listaPokemones[52] = p53;
        listaPokemones[53] = p54;
        listaPokemones[54] = p55;
        listaPokemones[55] = p56;
        listaPokemones[56] = p57;
        listaPokemones[57] = p58;
        listaPokemones[58] = p59;
        listaPokemones[59] = p60;
        Pokemones p61 = new Pokemones("Poliwhirls", 100, 1);
        Pokemones p62 = new Pokemones("Poliwrath", 100, 1);
        Pokemones p63 = new Pokemones("Abra", 100, 1);
        Pokemones p64 = new Pokemones("Kadabra", 100, 1);
        Pokemones p65 = new Pokemones("Alakazam", 100, 1);
        Pokemones p66 = new Pokemones("Machop", 100, 1);
        Pokemones p67 = new Pokemones("Machoke", 100, 1);
        Pokemones p68 = new Pokemones("Machamp", 100, 1);
        Pokemones p69 = new Pokemones("Bellsprout", 100, 1);
        Pokemones p70 = new Pokemones("Weepinbell", 100, 1);
        listaPokemones[60] = p61;
        listaPokemones[61] = p62;
        listaPokemones[62] = p63;
        listaPokemones[63] = p64;
        listaPokemones[64] = p65;
        listaPokemones[65] = p66;
        listaPokemones[66] = p67;
        listaPokemones[67] = p68;
        listaPokemones[68] = p69;
        listaPokemones[69] = p70;
        Pokemones p71 = new Pokemones("Victreebel", 100, 1);
        Pokemones p72 = new Pokemones("Tentacool", 100, 1);
        Pokemones p73 = new Pokemones("Tentacruel", 100, 1);
        Pokemones p74 = new Pokemones("Geodude", 100, 1);
        Pokemones p75 = new Pokemones("Graveler", 100, 1);
        Pokemones p76 = new Pokemones("Golem", 100, 1);
        Pokemones p77 = new Pokemones("Ponyta", 100, 1);
        Pokemones p78 = new Pokemones("Rapidash", 100, 1);
        Pokemones p79 = new Pokemones("Slowpoke", 100, 1);
        Pokemones p80 = new Pokemones("Slowbro", 100, 1);
        listaPokemones[70] = p71;
        listaPokemones[71] = p72;
        listaPokemones[72] = p73;
        listaPokemones[73] = p74;
        listaPokemones[74] = p75;
        listaPokemones[75] = p76;
        listaPokemones[76] = p77;
        listaPokemones[77] = p78;
        listaPokemones[78] = p79;
        listaPokemones[79] = p80;
        Pokemones p81 = new Pokemones("Magnemite", 100, 1);
        Pokemones p82 = new Pokemones("Magneton", 100, 1);
        Pokemones p83 = new Pokemones("Farfetchd", 100, 1);
        Pokemones p84 = new Pokemones("Doduo", 100, 1);
        Pokemones p85 = new Pokemones("Dodrio", 100, 1);
        Pokemones p86 = new Pokemones("Seel", 100, 1);
        Pokemones p87 = new Pokemones("Dewgong", 100, 1);
        Pokemones p88 = new Pokemones("Grimer", 100, 1);
        Pokemones p89 = new Pokemones("Muk", 100, 1);
        Pokemones p90 = new Pokemones("Shellder", 100, 1);
        listaPokemones[80] = p81;
        listaPokemones[81] = p82;
        listaPokemones[82] = p83;
        listaPokemones[83] = p84;
        listaPokemones[84] = p85;
        listaPokemones[85] = p86;
        listaPokemones[86] = p87;
        listaPokemones[87] = p88;
        listaPokemones[88] = p89;
        listaPokemones[89] = p90;
        Pokemones p91 = new Pokemones("Cloyster", 100, 1);
        Pokemones p92 = new Pokemones("Gastly", 100, 1);
        Pokemones p93 = new Pokemones("Haunter", 100, 1);
        Pokemones p94 = new Pokemones("Gengar", 100, 1);
        Pokemones p95 = new Pokemones("Onix", 100, 1);
        Pokemones p96 = new Pokemones("Drowzee", 100, 1);
        Pokemones p97 = new Pokemones("Hypno", 100, 1);
        Pokemones p98 = new Pokemones("Krabby", 100, 1);
        Pokemones p99 = new Pokemones("Kingler", 100, 1);
        Pokemones p100 = new Pokemones("Voltorb", 100, 1);
        listaPokemones[90] = p91;
        listaPokemones[91] = p92;
        listaPokemones[92] = p93;
        listaPokemones[93] = p94;
        listaPokemones[94] = p95;
        listaPokemones[95] = p96;
        listaPokemones[96] = p97;
        listaPokemones[97] = p98;
        listaPokemones[98] = p99;
        listaPokemones[99] = p100;
        Pokemones p101 = new Pokemones("Electrode", 100, 1);
        Pokemones p102 = new Pokemones("Exeggcute", 100, 1);
        Pokemones p103 = new Pokemones("Exeggutor", 100, 1);
        Pokemones p104 = new Pokemones("Cubone", 100, 1);
        Pokemones p105 = new Pokemones("Marowak", 100, 1);
        Pokemones p106 = new Pokemones("Hitmonlee", 100, 1);
        Pokemones p107 = new Pokemones("Hitmonchan", 100, 1);
        Pokemones p108 = new Pokemones("Lickitung", 100, 1);
        Pokemones p109 = new Pokemones("Koffing", 100, 1);
        Pokemones p110 = new Pokemones("Weezing", 100, 1);
        listaPokemones[100] = p101;
        listaPokemones[101] = p102;
        listaPokemones[102] = p103;
        listaPokemones[103] = p104;
        listaPokemones[104] = p105;
        listaPokemones[105] = p106;
        listaPokemones[106] = p107;
        listaPokemones[107] = p108;
        listaPokemones[108] = p109;
        listaPokemones[109] = p110;
        Pokemones p111 = new Pokemones("Rhyhorn", 100, 1);
        Pokemones p112 = new Pokemones("Rhydon", 100, 1);
        Pokemones p113 = new Pokemones("Chansey", 100, 1);
        Pokemones p114 = new Pokemones("Tangela", 100, 1);
        Pokemones p115 = new Pokemones("Kangaskhan", 100, 1);
        Pokemones p116 = new Pokemones("Horsea", 100, 1);
        Pokemones p117 = new Pokemones("Seadra", 100, 1);
        Pokemones p118 = new Pokemones("Goldeen", 100, 1);
        Pokemones p119 = new Pokemones("Seaking", 100, 1);
        Pokemones p120 = new Pokemones("Staryu", 100, 1);
        listaPokemones[110] = p111;
        listaPokemones[111] = p112;
        listaPokemones[112] = p113;
        listaPokemones[113] = p114;
        listaPokemones[114] = p115;
        listaPokemones[115] = p116;
        listaPokemones[116] = p117;
        listaPokemones[117] = p118;
        listaPokemones[118] = p119;
        listaPokemones[119] = p120;
        Pokemones p121 = new Pokemones("Starmie", 100, 1);
        Pokemones p122 = new Pokemones("MR. Mime", 100, 1);
        Pokemones p123 = new Pokemones("Scyther", 100, 1);
        Pokemones p124 = new Pokemones("Jynx", 100, 1);
        Pokemones p125 = new Pokemones("Electabuzz", 100, 1);
        Pokemones p126 = new Pokemones("Magmar", 100, 1);
        Pokemones p127 = new Pokemones("Pinsir", 100, 1);
        Pokemones p128 = new Pokemones("Tauros", 100, 1);
        Pokemones p129 = new Pokemones("Magikarp", 100, 1);
        Pokemones p130 = new Pokemones("Gyarados", 100, 1);
        listaPokemones[120] = p121;
        listaPokemones[121] = p122;
        listaPokemones[122] = p123;
        listaPokemones[123] = p124;
        listaPokemones[124] = p125;
        listaPokemones[125] = p126;
        listaPokemones[126] = p127;
        listaPokemones[127] = p128;
        listaPokemones[128] = p129;
        listaPokemones[129] = p130;
        Pokemones p131 = new Pokemones("Lapras", 100, 1);
        Pokemones p132 = new Pokemones("Ditto", 100, 1);
        Pokemones p133 = new Pokemones("Eevee", 100, 1);
        Pokemones p134 = new Pokemones("Vaporeon", 100, 1);
        Pokemones p135 = new Pokemones("Jolteon", 100, 1);
        Pokemones p136 = new Pokemones("Flareon", 100, 1);
        Pokemones p137 = new Pokemones("Porygon", 100, 1);
        Pokemones p138 = new Pokemones("Omanyte", 100, 1);
        Pokemones p139 = new Pokemones("Omastar", 100, 1);
        Pokemones p140 = new Pokemones("Kabuto", 100, 1);
        listaPokemones[130] = p131;
        listaPokemones[131] = p132;
        listaPokemones[132] = p133;
        listaPokemones[133] = p134;
        listaPokemones[134] = p135;
        listaPokemones[135] = p133;
        listaPokemones[136] = p137;
        listaPokemones[137] = p138;
        listaPokemones[138] = p139;
        listaPokemones[139] = p140;
        Pokemones p141 = new Pokemones("Kabutops", 100, 1);
        Pokemones p142 = new Pokemones("Aerodactyl", 100, 1);
        Pokemones p143 = new Pokemones("Snorlax", 100, 1);
        Pokemones p144 = new Pokemones("Articuno", 100, 1);
        Pokemones p145 = new Pokemones("Zapdos", 100, 1);
        Pokemones p146 = new Pokemones("Moltres", 100, 1);
        Pokemones p147 = new Pokemones("Dratini", 100, 1);
        Pokemones p148 = new Pokemones("Dragonair", 100, 1);
        Pokemones p149 = new Pokemones("Dragonite", 100, 1);
        Pokemones p150 = new Pokemones("Mewtwo", 100, 1);
        Pokemones p151 = new Pokemones("Mew", 100, 1);
        listaPokemones[140] = p141;
        listaPokemones[141] = p142;
        listaPokemones[142] = p143;
        listaPokemones[143] = p144;
        listaPokemones[144] = p145;
        listaPokemones[145] = p146;
        listaPokemones[146] = p147;
        listaPokemones[147] = p148;
        listaPokemones[148] = p149;
        listaPokemones[149] = p150;
        listaPokemones[150] = p151;
   
        return listaPokemones;
    }
    
    //el metodo que lo llame recibira la matriz con las imagenes, de la cual se elegiran algunos para el juego d ememoria que se les guardara en otro array
    //y se agregaran al panel y se les dara un ubicacion especifica 
    public JLabel [] imagenesPokemones(){
        //creamos los JLabels y los metemos en el arreglo
        JLabel label1 = new JLabel();
        JLabel label2 = new JLabel();
        JLabel label3 = new JLabel();
        JLabel label4 = new JLabel();
        JLabel label5 = new JLabel();
        JLabel label6 = new JLabel();
        JLabel label7 = new JLabel();
        JLabel label8 = new JLabel();
        JLabel label9 = new JLabel();
        JLabel label10 = new JLabel();
        JLabel label11 = new JLabel();
        JLabel label12 = new JLabel();
        JLabel label13 = new JLabel();
        JLabel label14 = new JLabel();
        JLabel label15 = new JLabel();
        JLabel label16 = new JLabel();
        JLabel label17 = new JLabel();
        JLabel label18 = new JLabel();
        JLabel label19 = new JLabel();
        JLabel label20 = new JLabel();
        JLabel label21 = new JLabel();
        JLabel label22 = new JLabel();
        JLabel label23 = new JLabel();
        JLabel label24 = new JLabel();
        JLabel label25 = new JLabel();
        JLabel label26 = new JLabel();
        JLabel label27 = new JLabel();
        JLabel label28 = new JLabel();
        JLabel label29 = new JLabel();
        JLabel label30 = new JLabel();
        JLabel label31 = new JLabel();
        JLabel label32 = new JLabel();
        JLabel label33 = new JLabel();
        JLabel label34 = new JLabel();
        JLabel label35 = new JLabel();
        JLabel label36 = new JLabel();
        JLabel label37 = new JLabel();
        JLabel label38 = new JLabel();
        JLabel label39 = new JLabel();
        JLabel label40 = new JLabel();
        JLabel label41 = new JLabel();
        JLabel label42 = new JLabel();
        JLabel label43 = new JLabel();
        JLabel label44 = new JLabel();
        JLabel label45 = new JLabel();
        JLabel label46 = new JLabel();
        JLabel label47 = new JLabel();
        JLabel label48 = new JLabel();
        JLabel label49 = new JLabel();
        JLabel label50 = new JLabel();
        JLabel label51 = new JLabel();
        JLabel label52 = new JLabel();
        JLabel label53 = new JLabel();
        JLabel label54 = new JLabel();
        JLabel label55 = new JLabel();
        JLabel label56 = new JLabel();
        JLabel label57 = new JLabel();
        JLabel label58 = new JLabel();
        JLabel label59 = new JLabel();
        JLabel label60 = new JLabel();
        JLabel label61 = new JLabel();
        JLabel label62 = new JLabel();
        JLabel label63 = new JLabel();
        JLabel label64 = new JLabel();
        JLabel label65 = new JLabel();
        JLabel label66 = new JLabel();
        JLabel label67 = new JLabel();
        JLabel label68 = new JLabel();
        JLabel label69 = new JLabel();
        JLabel label70 = new JLabel();
        JLabel label71 = new JLabel();
        JLabel label72 = new JLabel();
        JLabel label73 = new JLabel();
        JLabel label74 = new JLabel();
        JLabel label75 = new JLabel();
        JLabel label76 = new JLabel();
        JLabel label77 = new JLabel();
        JLabel label78 = new JLabel();
        JLabel label79 = new JLabel();
        JLabel label80 = new JLabel();
        JLabel label81 = new JLabel();
        JLabel label82 = new JLabel();
        JLabel label83 = new JLabel();
        JLabel label84 = new JLabel();
        JLabel label85 = new JLabel();
        JLabel label86 = new JLabel();
        JLabel label87 = new JLabel();
        JLabel label88 = new JLabel();
        JLabel label89 = new JLabel();
        JLabel label90 = new JLabel();
        JLabel label91 = new JLabel();
        JLabel label92 = new JLabel();
        JLabel label93 = new JLabel();
        JLabel label94 = new JLabel();
        JLabel label95 = new JLabel();
        JLabel label96 = new JLabel();
        JLabel label97 = new JLabel();
        JLabel label98 = new JLabel();
        JLabel label99 = new JLabel();
        JLabel label100 = new JLabel();
        JLabel label101 = new JLabel();
        JLabel label102 = new JLabel();
        JLabel label103 = new JLabel();
        JLabel label104 = new JLabel();
        JLabel label105 = new JLabel();
        JLabel label106 = new JLabel();
        JLabel label107 = new JLabel();
        JLabel label108 = new JLabel();
        JLabel label109 = new JLabel();
        JLabel label110 = new JLabel();
        JLabel label111 = new JLabel();
        JLabel label112 = new JLabel();
        JLabel label113 = new JLabel();
        JLabel label114 = new JLabel();
        JLabel label115 = new JLabel();
        JLabel label116 = new JLabel();
        JLabel label117 = new JLabel();
        JLabel label118 = new JLabel();
        JLabel label119 = new JLabel();
        JLabel label120 = new JLabel();
        JLabel label121 = new JLabel();
        JLabel label122 = new JLabel();
        JLabel label123 = new JLabel();
        JLabel label124 = new JLabel();
        JLabel label125 = new JLabel();
        JLabel label126 = new JLabel();
        JLabel label127 = new JLabel();
        JLabel label128 = new JLabel();
        JLabel label129 = new JLabel();
        JLabel label130 = new JLabel();
        JLabel label131 = new JLabel();
        JLabel label132 = new JLabel();
        JLabel label133 = new JLabel();
        JLabel label134 = new JLabel();
        JLabel label135 = new JLabel();
        JLabel label136 = new JLabel();
        JLabel label137 = new JLabel();
        JLabel label138 = new JLabel();
        JLabel label139 = new JLabel();
        JLabel label140 = new JLabel();
        JLabel label141 = new JLabel();
        JLabel label142 = new JLabel();
        JLabel label143 = new JLabel();
        JLabel label144 = new JLabel();
        JLabel label145 = new JLabel();
        JLabel label146 = new JLabel();
        JLabel label147 = new JLabel();
        JLabel label148 = new JLabel();
        JLabel label149 = new JLabel();
        JLabel label150 = new JLabel();
        JLabel label151 = new JLabel();

        
        //tamaño del primer label que les dara tamaño a los demas 
        label1.setSize(100, 95);
        //el tamaño de las imagenes seran iguales que sus labels usando solo el primero [0] para cambiar todos, si cambialos el primero, cambian los demas 
        ImageIcon imagen1 = new ImageIcon("imagenesPokemones/1.png");
        label1.setIcon(new ImageIcon(imagen1.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen2 = new ImageIcon("imagenesPokemones/2.png");
        label2.setIcon(new ImageIcon(imagen2.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen3 = new ImageIcon("imagenesPokemones/3.png");
        label3.setIcon(new ImageIcon(imagen3.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen4 = new ImageIcon("imagenesPokemones/4.png");
        label4.setIcon(new ImageIcon(imagen4.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen5 = new ImageIcon("imagenesPokemones/5.png");
        label5.setIcon(new ImageIcon(imagen5.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen6 = new ImageIcon("imagenesPokemones/6.png");
        label6.setIcon(new ImageIcon(imagen6.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen7 = new ImageIcon("imagenesPokemones/7.png");
        label7.setIcon(new ImageIcon(imagen7.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen8 = new ImageIcon("imagenesPokemones/8.png");
        label8.setIcon(new ImageIcon(imagen8.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen9 = new ImageIcon("imagenesPokemones/9.png");
        label9.setIcon(new ImageIcon(imagen9.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen10 = new ImageIcon("imagenesPokemones/10.png");
        label10.setIcon(new ImageIcon(imagen10.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen11 = new ImageIcon("imagenesPokemones/11.png");
        label11.setIcon(new ImageIcon(imagen11.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen12 = new ImageIcon("imagenesPokemones/12.png");
        label12.setIcon(new ImageIcon(imagen12.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen13 = new ImageIcon("imagenesPokemones/13.png");
        label13.setIcon(new ImageIcon(imagen13.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen14 = new ImageIcon("imagenesPokemones/14.png");
        label14.setIcon(new ImageIcon(imagen14.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen15 = new ImageIcon("imagenesPokemones/15.png");
        label15.setIcon(new ImageIcon(imagen15.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen16 = new ImageIcon("imagenesPokemones/16.png");
        label16.setIcon(new ImageIcon(imagen16.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen17 = new ImageIcon("imagenesPokemones/17.png");
        label17.setIcon(new ImageIcon(imagen17.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen18 = new ImageIcon("imagenesPokemones/18.png");
        label18.setIcon(new ImageIcon(imagen18.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen19 = new ImageIcon("imagenesPokemones/19.png");
        label19.setIcon(new ImageIcon(imagen19.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen20 = new ImageIcon("imagenesPokemones/20.png");
        label20.setIcon(new ImageIcon(imagen20.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        
        ImageIcon imagen21 = new ImageIcon("imagenesPokemones/21.png");
        label21.setIcon(new ImageIcon(imagen21.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen22 = new ImageIcon("imagenesPokemones/22.png");
        label22.setIcon(new ImageIcon(imagen22.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen23 = new ImageIcon("imagenesPokemones/23.png");
        label23.setIcon(new ImageIcon(imagen23.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen24 = new ImageIcon("imagenesPokemones/24.png");
        label24.setIcon(new ImageIcon(imagen24.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen25 = new ImageIcon("imagenesPokemones/25.png");
        label25.setIcon(new ImageIcon(imagen25.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen26 = new ImageIcon("imagenesPokemones/26.png");
        label26.setIcon(new ImageIcon(imagen26.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen27 = new ImageIcon("imagenesPokemones/27.png");
        label27.setIcon(new ImageIcon(imagen27.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen28 = new ImageIcon("imagenesPokemones/28.png");
        label28.setIcon(new ImageIcon(imagen28.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen29 = new ImageIcon("imagenesPokemones/29.png");
        label29.setIcon(new ImageIcon(imagen29.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen30 = new ImageIcon("imagenesPokemones/30.png");
        label30.setIcon(new ImageIcon(imagen30.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen31 = new ImageIcon("imagenesPokemones/031.png");
        label31.setIcon(new ImageIcon(imagen31.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen32 = new ImageIcon("imagenesPokemones/032.png");
        label32.setIcon(new ImageIcon(imagen32.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen33 = new ImageIcon("imagenesPokemones/033.png");
        label13.setIcon(new ImageIcon(imagen13.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen34 = new ImageIcon("imagenesPokemones/034.png");
        label34.setIcon(new ImageIcon(imagen34.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen35 = new ImageIcon("imagenesPokemones/035.png");
        label35.setIcon(new ImageIcon(imagen35.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen36 = new ImageIcon("imagenesPokemones/036.png");
        label36.setIcon(new ImageIcon(imagen36.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen37 = new ImageIcon("imagenesPokemones/037.png");
        label37.setIcon(new ImageIcon(imagen37.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen38 = new ImageIcon("imagenesPokemones/038.png");
        label38.setIcon(new ImageIcon(imagen38.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen39 = new ImageIcon("imagenesPokemones/039.png");
        label39.setIcon(new ImageIcon(imagen39.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen40 = new ImageIcon("imagenesPokemones/040.png");
        label40.setIcon(new ImageIcon(imagen40.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen41 = new ImageIcon("imagenesPokemones/041.png");
        label41.setIcon(new ImageIcon(imagen41.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen42 = new ImageIcon("imagenesPokemones/042.png");
        label42.setIcon(new ImageIcon(imagen42.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen43 = new ImageIcon("imagenesPokemones/043.png");
        label43.setIcon(new ImageIcon(imagen43.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen44 = new ImageIcon("imagenesPokemones/044.png");
        label44.setIcon(new ImageIcon(imagen44.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen45 = new ImageIcon("imagenesPokemones/045.png");
        label45.setIcon(new ImageIcon(imagen45.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen46 = new ImageIcon("imagenesPokemones/046.png");
        label46.setIcon(new ImageIcon(imagen46.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen47 = new ImageIcon("imagenesPokemones/047.png");
        label47.setIcon(new ImageIcon(imagen47.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen48 = new ImageIcon("imagenesPokemones/048.png");
        label48.setIcon(new ImageIcon(imagen48.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen49 = new ImageIcon("imagenesPokemones/049.png");
        label49.setIcon(new ImageIcon(imagen49.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen50 = new ImageIcon("imagenesPokemones/050.png");
        label50.setIcon(new ImageIcon(imagen50.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen51 = new ImageIcon("imagenesPokemones/051.png");
        label51.setIcon(new ImageIcon(imagen51.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen52 = new ImageIcon("imagenesPokemones/052.png");
        label52.setIcon(new ImageIcon(imagen52.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen53 = new ImageIcon("imagenesPokemones/053.png");
        label53.setIcon(new ImageIcon(imagen53.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen54 = new ImageIcon("imagenesPokemones/054.png");
        label54.setIcon(new ImageIcon(imagen54.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen55 = new ImageIcon("imagenesPokemones/055.png");
        label55.setIcon(new ImageIcon(imagen55.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen56 = new ImageIcon("imagenesPokemones/056.png");
        label56.setIcon(new ImageIcon(imagen56.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen57 = new ImageIcon("imagenesPokemones/057.png");
        label57.setIcon(new ImageIcon(imagen57.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen58 = new ImageIcon("imagenesPokemones/058.png");
        label58.setIcon(new ImageIcon(imagen58.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen59 = new ImageIcon("imagenesPokemones/059.png");
        label59.setIcon(new ImageIcon(imagen59.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen60 = new ImageIcon("imagenesPokemones/060.png");
        label60.setIcon(new ImageIcon(imagen60.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen61 = new ImageIcon("imagenesPokemones/061.png");
        label61.setIcon(new ImageIcon(imagen61.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen62 = new ImageIcon("imagenesPokemones/062.png");
        label62.setIcon(new ImageIcon(imagen62.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen63 = new ImageIcon("imagenesPokemones/063.png");
        label63.setIcon(new ImageIcon(imagen63.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen64 = new ImageIcon("imagenesPokemones/064.png");
        label64.setIcon(new ImageIcon(imagen64.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen65 = new ImageIcon("imagenesPokemones/065.png");
        label65.setIcon(new ImageIcon(imagen65.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen66 = new ImageIcon("imagenesPokemones/066.png");
        label66.setIcon(new ImageIcon(imagen66.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen67 = new ImageIcon("imagenesPokemones/067.png");
        label67.setIcon(new ImageIcon(imagen67.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen68 = new ImageIcon("imagenesPokemones/068.png");
        label68.setIcon(new ImageIcon(imagen68.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen69 = new ImageIcon("imagenesPokemones/069.png");
        label69.setIcon(new ImageIcon(imagen69.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen70 = new ImageIcon("imagenesPokemones/070.png");
        label70.setIcon(new ImageIcon(imagen70.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen71 = new ImageIcon("imagenesPokemones/071.png");
        label71.setIcon(new ImageIcon(imagen71.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen72 = new ImageIcon("imagenesPokemones/072.png");
        label72.setIcon(new ImageIcon(imagen72.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen73 = new ImageIcon("imagenesPokemones/073.png");
        label73.setIcon(new ImageIcon(imagen73.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen74 = new ImageIcon("imagenesPokemones/074.png");
        label74.setIcon(new ImageIcon(imagen74.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen75 = new ImageIcon("imagenesPokemones/075.png");
        label75.setIcon(new ImageIcon(imagen75.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen76 = new ImageIcon("imagenesPokemones/076.png");
        label76.setIcon(new ImageIcon(imagen76.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen77 = new ImageIcon("imagenesPokemones/077.png");
        label77.setIcon(new ImageIcon(imagen77.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen78 = new ImageIcon("imagenesPokemones/078.png");
        label78.setIcon(new ImageIcon(imagen78.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen79 = new ImageIcon("imagenesPokemones/079.png");
        label79.setIcon(new ImageIcon(imagen79.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen80 = new ImageIcon("imagenesPokemones/080.png");
        label80.setIcon(new ImageIcon(imagen80.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen81 = new ImageIcon("imagenesPokemones/081.png");
        label81.setIcon(new ImageIcon(imagen81.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen82 = new ImageIcon("imagenesPokemones/082.png");
        label82.setIcon(new ImageIcon(imagen82.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen83 = new ImageIcon("imagenesPokemones/083.png");
        label83.setIcon(new ImageIcon(imagen83.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen84 = new ImageIcon("imagenesPokemones/084.png");
        label84.setIcon(new ImageIcon(imagen84.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen85 = new ImageIcon("imagenesPokemones/085.png");
        label85.setIcon(new ImageIcon(imagen85.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen86 = new ImageIcon("imagenesPokemones/086.png");
        label86.setIcon(new ImageIcon(imagen86.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen87 = new ImageIcon("imagenesPokemones/087.png");
        label87.setIcon(new ImageIcon(imagen87.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen88 = new ImageIcon("imagenesPokemones/088.png");
        label88.setIcon(new ImageIcon(imagen88.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen89 = new ImageIcon("imagenesPokemones/089.png");
        label89.setIcon(new ImageIcon(imagen89.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen90 = new ImageIcon("imagenesPokemones/090.png");
        label90.setIcon(new ImageIcon(imagen90.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen91 = new ImageIcon("imagenesPokemones/091.png");
        label91.setIcon(new ImageIcon(imagen91.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen92 = new ImageIcon("imagenesPokemones/092.png");
        label92.setIcon(new ImageIcon(imagen92.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen93 = new ImageIcon("imagenesPokemones/093.png");
        label93.setIcon(new ImageIcon(imagen93.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen94 = new ImageIcon("imagenesPokemones/094.png");
        label94.setIcon(new ImageIcon(imagen94.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen95 = new ImageIcon("imagenesPokemones/095.png");
        label95.setIcon(new ImageIcon(imagen95.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen96 = new ImageIcon("imagenesPokemones/096.png");
        label96.setIcon(new ImageIcon(imagen96.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen97 = new ImageIcon("imagenesPokemones/097.png");
        label97.setIcon(new ImageIcon(imagen97.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen98 = new ImageIcon("imagenesPokemones/098.png");
        label98.setIcon(new ImageIcon(imagen98.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen99 = new ImageIcon("imagenesPokemones/099.png");
        label99.setIcon(new ImageIcon(imagen99.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen100 = new ImageIcon("imagenesPokemones/100.png");
        label100.setIcon(new ImageIcon(imagen100.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen101 = new ImageIcon("imagenesPokemones/101.png");
        label101.setIcon(new ImageIcon(imagen101.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen102 = new ImageIcon("imagenesPokemones/102.png");
        label102.setIcon(new ImageIcon(imagen102.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen103 = new ImageIcon("imagenesPokemones/103.png");
        label103.setIcon(new ImageIcon(imagen103.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen104 = new ImageIcon("imagenesPokemones/104.png");
        label104.setIcon(new ImageIcon(imagen104.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen105 = new ImageIcon("imagenesPokemones/105.png");
        label105.setIcon(new ImageIcon(imagen105.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen106 = new ImageIcon("imagenesPokemones/106.png");
        label106.setIcon(new ImageIcon(imagen106.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen107 = new ImageIcon("imagenesPokemones/107.png");
        label107.setIcon(new ImageIcon(imagen107.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen108 = new ImageIcon("imagenesPokemones/108.png");
        label108.setIcon(new ImageIcon(imagen108.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen109 = new ImageIcon("imagenesPokemones/109.png");
        label109.setIcon(new ImageIcon(imagen109.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
         ImageIcon imagen110 = new ImageIcon("imagenesPokemones/110.png");
        label110.setIcon(new ImageIcon(imagen110.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen111 = new ImageIcon("imagenesPokemones/111.png");
        label111.setIcon(new ImageIcon(imagen111.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen112 = new ImageIcon("imagenesPokemones/112.png");
        label112.setIcon(new ImageIcon(imagen112.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen113 = new ImageIcon("imagenesPokemones/113.png");
        label113.setIcon(new ImageIcon(imagen113.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen114 = new ImageIcon("imagenesPokemones/114.png");
        label114.setIcon(new ImageIcon(imagen114.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen115 = new ImageIcon("imagenesPokemones/115.png");
        label115.setIcon(new ImageIcon(imagen115.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen116 = new ImageIcon("imagenesPokemones/116.png");
        label116.setIcon(new ImageIcon(imagen116.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen117 = new ImageIcon("imagenesPokemones/117.png");
        label117.setIcon(new ImageIcon(imagen117.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen118 = new ImageIcon("imagenesPokemones/118.png");
        label118.setIcon(new ImageIcon(imagen118.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen119 = new ImageIcon("imagenesPokemones/119.png");
        label119.setIcon(new ImageIcon(imagen119.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen120 = new ImageIcon("imagenesPokemones/120.png");
        label120.setIcon(new ImageIcon(imagen120.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen121 = new ImageIcon("imagenesPokemones/121.png");
        label121.setIcon(new ImageIcon(imagen121.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen122 = new ImageIcon("imagenesPokemones/122.png");
        label122.setIcon(new ImageIcon(imagen122.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen123 = new ImageIcon("imagenesPokemones/123.png");
        label123.setIcon(new ImageIcon(imagen123.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen124 = new ImageIcon("imagenesPokemones/124.png");
        label124.setIcon(new ImageIcon(imagen124.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen125 = new ImageIcon("imagenesPokemones/125.png");
        label125.setIcon(new ImageIcon(imagen125.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen126 = new ImageIcon("imagenesPokemones/126.png");
        label126.setIcon(new ImageIcon(imagen126.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen127 = new ImageIcon("imagenesPokemones/127.png");
        label127.setIcon(new ImageIcon(imagen127.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen128 = new ImageIcon("imagenesPokemones/128.png");
        label128.setIcon(new ImageIcon(imagen128.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen129 = new ImageIcon("imagenesPokemones/129.png");
        label129.setIcon(new ImageIcon(imagen129.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen130 = new ImageIcon("imagenesPokemones/130.png");
        label130.setIcon(new ImageIcon(imagen130.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen131 = new ImageIcon("imagenesPokemones/131.png");
        label131.setIcon(new ImageIcon(imagen131.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen132 = new ImageIcon("imagenesPokemones/132.png");
        label132.setIcon(new ImageIcon(imagen132.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen133 = new ImageIcon("imagenesPokemones/133.png");
        label133.setIcon(new ImageIcon(imagen133.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen134 = new ImageIcon("imagenesPokemones/134.png");
        label134.setIcon(new ImageIcon(imagen134.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen135 = new ImageIcon("imagenesPokemones/135.png");
        label135.setIcon(new ImageIcon(imagen135.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen136 = new ImageIcon("imagenesPokemones/136.png");
        label136.setIcon(new ImageIcon(imagen136.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen137 = new ImageIcon("imagenesPokemones/137.png");
        label137.setIcon(new ImageIcon(imagen137.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen138 = new ImageIcon("imagenesPokemones/138.png");
        label138.setIcon(new ImageIcon(imagen138.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen139 = new ImageIcon("imagenesPokemones/139.png");
        label9.setIcon(new ImageIcon(imagen9.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen140 = new ImageIcon("imagenesPokemones/140.png");
        label140.setIcon(new ImageIcon(imagen140.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen141 = new ImageIcon("imagenesPokemones/141.png");
        label141.setIcon(new ImageIcon(imagen141.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen142 = new ImageIcon("imagenesPokemones/142.png");
        label142.setIcon(new ImageIcon(imagen142.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen143 = new ImageIcon("imagenesPokemones/143.png");
        label143.setIcon(new ImageIcon(imagen143.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen144 = new ImageIcon("imagenesPokemones/144.png");
        label144.setIcon(new ImageIcon(imagen144.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen145 = new ImageIcon("imagenesPokemones/145.png");
        label145.setIcon(new ImageIcon(imagen145.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen146 = new ImageIcon("imagenesPokemones/146.png");
        label146.setIcon(new ImageIcon(imagen146.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen147 = new ImageIcon("imagenesPokemones/147.png");
        label147.setIcon(new ImageIcon(imagen147.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen148 = new ImageIcon("imagenesPokemones/148.png");
        label148.setIcon(new ImageIcon(imagen148.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen149 = new ImageIcon("imagenesPokemones/149.png");
        label149.setIcon(new ImageIcon(imagen149.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen150 = new ImageIcon("imagenesPokemones/150.png");
        label150.setIcon(new ImageIcon(imagen150.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        ImageIcon imagen151 = new ImageIcon("imagenesPokemones/151.png");
        label151.setIcon(new ImageIcon(imagen151.getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH)));
        
        
        //ingresar labels al array
        imagenesPokemones[0]=label1;
        imagenesPokemones[1]=label2;
        imagenesPokemones[2]=label3;
        imagenesPokemones[3]=label4;
        imagenesPokemones[4]=label5;
        imagenesPokemones[5]=label6;
        imagenesPokemones[6]=label7;
        imagenesPokemones[7]=label8;
        imagenesPokemones[8]=label9;
        imagenesPokemones[9]=label10;
        
        imagenesPokemones[10]=label1;
        imagenesPokemones[11]=label2;
        imagenesPokemones[12]=label3;
        imagenesPokemones[13]=label4;
        imagenesPokemones[14]=label5;
        imagenesPokemones[15]=label6;
        imagenesPokemones[16]=label7;
        imagenesPokemones[17]=label8;
        imagenesPokemones[18]=label9;
        imagenesPokemones[19]=label20;
        
        imagenesPokemones[20]=label21;
        imagenesPokemones[21]=label22;
        imagenesPokemones[22]=label23;
        imagenesPokemones[23]=label24;
        imagenesPokemones[24]=label25;
        imagenesPokemones[25]=label26;
        imagenesPokemones[26]=label27;
        imagenesPokemones[27]=label28;
        imagenesPokemones[28]=label29;
        imagenesPokemones[29]=label30;
        
        imagenesPokemones[30]=label31;
        imagenesPokemones[31]=label32;
        imagenesPokemones[32]=label33;
        imagenesPokemones[33]=label34;
        imagenesPokemones[34]=label35;
        imagenesPokemones[35]=label36;
        imagenesPokemones[36]=label37;
        imagenesPokemones[37]=label38;
        imagenesPokemones[38]=label39;
        imagenesPokemones[39]=label40;
        
        imagenesPokemones[40]=label41;
        imagenesPokemones[41]=label42;
        imagenesPokemones[42]=label43;
        imagenesPokemones[43]=label44;
        imagenesPokemones[44]=label45;
        imagenesPokemones[45]=label46;
        imagenesPokemones[46]=label47;
        imagenesPokemones[47]=label48;
        imagenesPokemones[48]=label49;
        imagenesPokemones[49]=label50;
        
        imagenesPokemones[50]=label51;
        imagenesPokemones[51]=label52;
        imagenesPokemones[52]=label53;
        imagenesPokemones[53]=label54;
        imagenesPokemones[54]=label55;
        imagenesPokemones[55]=label56;
        imagenesPokemones[56]=label57;
        imagenesPokemones[57]=label58;
        imagenesPokemones[58]=label59;
        imagenesPokemones[59]=label60;
        
        imagenesPokemones[60]=label61;
        imagenesPokemones[61]=label62;
        imagenesPokemones[62]=label63;
        imagenesPokemones[63]=label64;
        imagenesPokemones[64]=label65;
        imagenesPokemones[65]=label66;
        imagenesPokemones[66]=label67;
        imagenesPokemones[67]=label68;
        imagenesPokemones[68]=label69;
        imagenesPokemones[69]=label70;
        
        imagenesPokemones[70]=label71;
        imagenesPokemones[71]=label72;
        imagenesPokemones[72]=label73;
        imagenesPokemones[73]=label74;
        imagenesPokemones[74]=label75;
        imagenesPokemones[75]=label76;
        imagenesPokemones[76]=label77;
        imagenesPokemones[77]=label78;
        imagenesPokemones[78]=label79;
        imagenesPokemones[79]=label80;
        
        imagenesPokemones[80]=label81;
        imagenesPokemones[81]=label82;
        imagenesPokemones[82]=label83;
        imagenesPokemones[83]=label84;
        imagenesPokemones[84]=label85;
        imagenesPokemones[85]=label86;
        imagenesPokemones[86]=label87;
        imagenesPokemones[87]=label88;
        imagenesPokemones[88]=label89;
        imagenesPokemones[89]=label90;
        
        imagenesPokemones[90]=label91;
        imagenesPokemones[91]=label92;
        imagenesPokemones[92]=label93;
        imagenesPokemones[93]=label94;
        imagenesPokemones[94]=label95;
        imagenesPokemones[95]=label96;
        imagenesPokemones[96]=label97;
        imagenesPokemones[97]=label98;
        imagenesPokemones[98]=label99;
        imagenesPokemones[99]=label110;
        
        imagenesPokemones[100]=label101;
        imagenesPokemones[101]=label102;
        imagenesPokemones[102]=label103;
        imagenesPokemones[103]=label104;
        imagenesPokemones[104]=label105;
        imagenesPokemones[105]=label106;
        imagenesPokemones[106]=label107;
        imagenesPokemones[107]=label108;
        imagenesPokemones[108]=label109;
        imagenesPokemones[109]=label110;
        
        imagenesPokemones[110]=label111;
        imagenesPokemones[111]=label112;
        imagenesPokemones[112]=label113;
        imagenesPokemones[113]=label114;
        imagenesPokemones[114]=label115;
        imagenesPokemones[115]=label116;
        imagenesPokemones[116]=label117;
        imagenesPokemones[117]=label118;
        imagenesPokemones[118]=label119;
        imagenesPokemones[119]=label120;
        
        imagenesPokemones[120]=label121;
        imagenesPokemones[121]=label122;
        imagenesPokemones[122]=label123;
        imagenesPokemones[123]=label124;
        imagenesPokemones[124]=label125;
        imagenesPokemones[125]=label126;
        imagenesPokemones[126]=label127;
        imagenesPokemones[127]=label128;
        imagenesPokemones[128]=label129;
        imagenesPokemones[129]=label130;
        
        imagenesPokemones[130]=label131;
        imagenesPokemones[131]=label132;
        imagenesPokemones[132]=label133;
        imagenesPokemones[133]=label134;
        imagenesPokemones[134]=label135;
        imagenesPokemones[135]=label136;
        imagenesPokemones[136]=label137;
        imagenesPokemones[137]=label138;
        imagenesPokemones[138]=label139;
        imagenesPokemones[139]=label140;
        
        imagenesPokemones[140]=label141;
        imagenesPokemones[141]=label142;
        imagenesPokemones[142]=label143;
        imagenesPokemones[143]=label144;
        imagenesPokemones[144]=label145;
        imagenesPokemones[145]=label146;
        imagenesPokemones[146]=label147;
        imagenesPokemones[147]=label148;
        imagenesPokemones[148]=label149;
        imagenesPokemones[149]=label150;
        imagenesPokemones[150]=label51;

        
        
        
        return imagenesPokemones;
    }
    
}
